### PR TITLE
Add inline annotation for Streaming_stream.

### PR DESCRIPTION
**Pull request by rizo**
It seems like flambda was not automatically inlining the stacked consumers (i.e. folds). With explicit inline annotations the results look quite different:

```
ocamlfind opt -O3 -unbox-closures -unbox-closures-factor 20 -package iter -package gen -package core_kernel -package base -package batteries -package benchmark -package containers -package oseq -linkpkg bench.ml -o bench.native
./bench.native
Throughputs for "gen", "gen_no_optim", "g", "g_exn", "core.sequence", "base.sequence", "cps", "cps2", "fold", "iter", "list", "lazy_list", "ulist", "uncons", "coroutine", "batseq", "std_seq", "oseq", "streaming" each running 2 times for at least 3 CPU seconds:
          gen:  3.33 WALL ( 3.31 usr +  0.01 sys =  3.32 CPU) @ 68.09/s (n=226)
                3.42 WALL ( 3.40 usr +  0.01 sys =  3.41 CPU) @ 66.35/s (n=226)
 gen_no_optim:  3.28 WALL ( 3.25 usr +  0.01 sys =  3.26 CPU) @ 54.58/s (n=178)
                3.19 WALL ( 3.18 usr +  0.01 sys =  3.19 CPU) @ 55.87/s (n=178)
            g:  3.18 WALL ( 3.17 usr +  0.00 sys =  3.17 CPU) @ 133.31/s (n=423)
                3.19 WALL ( 3.19 usr +  0.01 sys =  3.19 CPU) @ 132.56/s (n=423)
        g_exn:  3.19 WALL ( 3.18 usr +  0.01 sys =  3.19 CPU) @ 109.54/s (n=349)
                3.21 WALL ( 3.19 usr +  0.01 sys =  3.20 CPU) @ 108.95/s (n=349)
core.sequence:  3.06 WALL ( 3.05 usr +  0.01 sys =  3.06 CPU) @ 77.25/s (n=236)
                3.12 WALL ( 3.09 usr +  0.01 sys =  3.10 CPU) @ 73.47/s (n=228)
base.sequence:  3.01 WALL ( 3.00 usr +  0.01 sys =  3.01 CPU) @ 75.50/s (n=227)
                3.09 WALL ( 3.07 usr +  0.01 sys =  3.08 CPU) @ 73.67/s (n=227)
          cps:  3.12 WALL ( 3.10 usr +  0.01 sys =  3.11 CPU) @ 26.67/s (n=83)
                3.15 WALL ( 3.13 usr +  0.01 sys =  3.14 CPU) @ 26.46/s (n=83)
         cps2:  3.10 WALL ( 3.08 usr +  0.01 sys =  3.09 CPU) @ 26.55/s (n=82)
                3.01 WALL ( 3.00 usr +  0.00 sys =  3.01 CPU) @ 27.28/s (n=82)
         fold:  3.13 WALL ( 3.12 usr +  0.01 sys =  3.13 CPU) @ 232.42/s (n=727)
                3.12 WALL ( 3.11 usr +  0.00 sys =  3.11 CPU) @ 233.46/s (n=727)
         iter:  3.02 WALL ( 3.01 usr +  0.00 sys =  3.02 CPU) @ 249.38/s (n=752)
                3.01 WALL ( 3.01 usr +  0.00 sys =  3.01 CPU) @ 249.81/s (n=752)
         list:  3.34 WALL ( 3.32 usr +  0.02 sys =  3.34 CPU) @  5.99/s (n=20)
                3.09 WALL ( 3.08 usr +  0.01 sys =  3.09 CPU) @  6.48/s (n=20)
    lazy_list:  3.08 WALL ( 3.07 usr +  0.00 sys =  3.08 CPU) @ 10.72/s (n=33)
                3.04 WALL ( 3.03 usr +  0.00 sys =  3.04 CPU) @ 10.54/s (n=32)
        ulist:  3.23 WALL ( 3.22 usr +  0.01 sys =  3.22 CPU) @ 74.49/s (n=240)
                3.32 WALL ( 3.30 usr +  0.01 sys =  3.31 CPU) @ 72.54/s (n=240)
       uncons:  3.11 WALL ( 3.10 usr +  0.01 sys =  3.11 CPU) @ 74.07/s (n=230)
                3.10 WALL ( 3.09 usr +  0.01 sys =  3.09 CPU) @ 74.32/s (n=230)
    coroutine:  3.45 WALL ( 3.39 usr +  0.03 sys =  3.42 CPU) @ 66.12/s (n=226)
                3.99 WALL ( 3.88 usr +  0.04 sys =  3.91 CPU) @ 57.75/s (n=226)
       batseq:  3.43 WALL ( 3.39 usr +  0.02 sys =  3.41 CPU) @ 51.90/s (n=177)
                3.49 WALL ( 3.46 usr +  0.02 sys =  3.48 CPU) @ 50.92/s (n=177)
      std_seq:  3.23 WALL ( 3.22 usr +  0.01 sys =  3.23 CPU) @ 68.78/s (n=222)
                3.39 WALL ( 3.34 usr +  0.02 sys =  3.36 CPU) @ 66.08/s (n=222)
         oseq:  3.44 WALL ( 3.41 usr +  0.01 sys =  3.43 CPU) @ 64.75/s (n=222)
                3.21 WALL ( 3.19 usr +  0.01 sys =  3.20 CPU) @ 69.39/s (n=222)
    streaming:  3.07 WALL ( 3.06 usr +  0.01 sys =  3.07 CPU) @ 611.55/s (n=1876)
                3.04 WALL ( 3.04 usr +  0.00 sys =  3.04 CPU) @ 638.12/s (n=1940)
                Rate        list lazy_list   cps  cps2 batseq gen_no_optim coroutine  oseq   gen std_seq  ulist uncons base.sequence core.sequence g_exn    g fold iter streaming
         list 6.23+-0.23/s    --      -41%  -77%  -77%   -88%         -89%      -90%  -91%  -91%    -91%   -92%   -92%          -92%          -92%  -94% -95% -97% -98%      -99%
    lazy_list 10.6+- 0.1/s   70%        --  -60%  -61%   -79%         -81%      -83%  -84%  -84%    -84%   -86%   -86%          -86%          -86%  -90% -92% -95% -96%      -98%
          cps 26.6+- 0.1/s  326%      150%    -- [-1%]   -48%         -52%      -57%  -60%  -60%    -61%   -64%   -64%          -64%          -65%  -76% -80% -89% -89%      -96%
         cps2 26.9+- 0.3/s  332%      153%  [1%]    --   -48%         -51%      -57%  -60%  -60%    -60%   -63%   -64%          -64%          -64%  -75% -80% -88% -89%      -96%
       batseq 51.4+- 0.5/s  725%      384%   93%   91%     --          -7%    [-17%]  -23%  -24%    -24%   -30%   -31%          -31%          -32%  -53% -61% -78% -79%      -92%
 gen_no_optim 55.2+- 0.6/s  786%      420%  108%  105%     7%           --    [-11%]  -18%  -18%    -18%   -25%   -26%          -26%          -27%  -49% -58% -76% -78%      -91%
    coroutine 61.9+- 4.0/s  894%      483%  133%  130%  [20%]        [12%]        -- [-8%] [-8%]   [-8%] [-16%] [-17%]        [-17%]        [-18%]  -43% -53% -73% -75%      -90%
         oseq 67.1+- 2.2/s  976%      531%  152%  149%    30%          21%      [8%]    -- [-0%]   [-1%]  [-9%] [-10%]        [-10%]        [-11%]  -39% -50% -71% -73%      -89%
          gen 67.2+- 0.8/s  978%      532%  153%  150%    31%          22%      [9%]  [0%]    --   [-0%]    -9%    -9%          -10%        [-11%]  -38% -49% -71% -73%      -89%
      std_seq 67.4+- 1.3/s  982%      534%  154%  151%    31%          22%      [9%]  [1%]  [0%]      --  [-8%]    -9%          -10%        [-11%]  -38% -49% -71% -73%      -89%
        ulist 73.5+- 0.9/s 1079%      592%  177%  173%    43%          33%     [19%] [10%]    9%    [9%]     --  [-1%]         [-1%]         [-2%]  -33% -45% -68% -71%      -88%
       uncons 74.2+- 0.1/s 1090%      598%  179%  176%    44%          34%     [20%] [11%]   10%     10%   [1%]     --         [-1%]         [-2%]  -32% -44% -68% -70%      -88%
base.sequence 74.6+- 0.9/s 1096%      602%  181%  177%    45%          35%     [20%] [11%]   11%     11%   [1%]   [1%]            --         [-1%]  -32% -44% -68% -70%      -88%
core.sequence 75.4+- 1.8/s 1109%      609%  184%  180%    47%          36%     [22%] [12%] [12%]   [12%]   [3%]   [2%]          [1%]            --  -31% -43% -68% -70%      -88%
        g_exn  109+-   0/s 1652%      928%  311%  306%   113%          98%       76%   63%   63%     62%    49%    47%           46%           45%    -- -18% -53% -56%      -83%
            g  133+-   0/s 2032%     1151%  400%  394%   159%         141%      115%   98%   98%     97%    81%    79%           78%           76%   22%   -- -43% -47%      -79%
         fold  233+-   0/s 3637%     2092%  777%  766%   353%         322%      276%  247%  247%    245%   217%   214%          212%          209%  113%  75%   --  -7%      -63%
         iter  250+-   0/s 3904%     2248%  839%  827%   386%         352%      303%  272%  271%    270%   240%   236%          235%          231%  128%  88%   7%   --      -60%
    streaming  625+-  13/s 9923%     5779% 2252% 2222%  1115%        1031%      909%  832%  830%    827%   750%   742%          738%          729%  472% 370% 168% 150%        --
```

CC @c-cube @Fourchaux – could you double-check these results?

### CODE REVIEW

**Comment by Fourchaux** [comment]
@rizo I confirm your results. Well done. :smiley:
But check a second test...
```
ocamlfind opt -O3 -unbox-closures -unbox-closures-factor 20 -package iter -package gen -package core_kernel -package base -package batteries -package benchmark -package containers -package oseq -linkpkg bench.ml -o bench.native
./bench.native
Throughputs for "gen", "gen_no_optim", "g", "g_exn", "core.sequence", "base.sequence", "cps", "cps2", "fold", "iter", "list", "lazy_list", "ulist", "uncons", "coroutine", "batseq", "std_seq", "oseq", "streaming" each running 2 times for at least 3 CPU seconds:
          gen:  3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 48.63/s (n=153)
                3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 48.54/s (n=153)
 gen_no_optim:  3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 41.55/s (n=131)
                3.16 WALL ( 3.16 usr +  0.00 sys =  3.16 CPU) @ 41.40/s (n=131)
            g:  3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 94.19/s (n=297)
                3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 94.31/s (n=297)
        g_exn:  3.14 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 85.89/s (n=270)
                3.13 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 86.22/s (n=270)
core.sequence:  3.14 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 60.47/s (n=190)
                3.13 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 60.71/s (n=190)
base.sequence:  3.16 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 59.30/s (n=187)
                3.16 WALL ( 3.16 usr +  0.00 sys =  3.16 CPU) @ 59.15/s (n=187)
          cps:  3.12 WALL ( 3.11 usr +  0.00 sys =  3.11 CPU) @ 19.91/s (n=62)
                3.12 WALL ( 3.12 usr +  0.00 sys =  3.12 CPU) @ 19.87/s (n=62)
         cps2:  3.13 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 19.79/s (n=62)
                3.14 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 19.77/s (n=62)
         fold:  3.17 WALL ( 3.17 usr +  0.00 sys =  3.17 CPU) @ 158.49/s (n=502)
                3.16 WALL ( 3.16 usr +  0.00 sys =  3.16 CPU) @ 158.91/s (n=502)
         iter:  3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 298.31/s (n=940)
                3.16 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 298.04/s (n=940)
         list:  3.09 WALL ( 3.07 usr +  0.02 sys =  3.09 CPU) @  5.51/s (n=17)
                3.13 WALL ( 3.11 usr +  0.02 sys =  3.12 CPU) @  5.44/s (n=17)
    lazy_list:  3.05 WALL ( 3.04 usr +  0.00 sys =  3.04 CPU) @  7.88/s (n=24)
                3.04 WALL ( 3.04 usr +  0.00 sys =  3.04 CPU) @  7.89/s (n=24)
        ulist:  3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 56.45/s (n=178)
                3.14 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 56.72/s (n=178)
       uncons:  3.15 WALL ( 3.14 usr +  0.00 sys =  3.15 CPU) @ 58.48/s (n=184)
                3.14 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 58.59/s (n=184)
    coroutine:  3.05 WALL ( 3.05 usr +  0.00 sys =  3.05 CPU) @ 50.82/s (n=155)
                3.08 WALL ( 3.08 usr +  0.00 sys =  3.08 CPU) @ 50.36/s (n=155)
       batseq:  3.13 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 43.09/s (n=135)
                3.13 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 43.13/s (n=135)
      std_seq:  3.16 WALL ( 3.16 usr +  0.00 sys =  3.16 CPU) @ 51.35/s (n=162)
                3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 51.42/s (n=162)
         oseq:  3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 51.77/s (n=163)
                3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 51.71/s (n=163)
    streaming:  3.14 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 533.01/s (n=1676)
                3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 531.68/s (n=1676)
                Rate        list lazy_list  cps2   cps gen_no_optim batseq  gen coroutine std_seq oseq ulist uncons base.sequence core.sequence g_exn    g fold iter streaming
         list 5.48+-0.03/s    --      -31%  -72%  -72%         -87%   -87% -89%      -89%    -89% -89%  -90%   -91%          -91%          -91%  -94% -94% -97% -98%      -99%
    lazy_list 7.89+-0.00/s   44%        --  -60%  -60%         -81%   -82% -84%      -84%    -85% -85%  -86%   -87%          -87%          -87%  -91% -92% -95% -97%      -99%
         cps2 19.8+- 0.0/s  261%      151%    --   -1%         -52%   -54% -59%      -61%    -61% -62%  -65%   -66%          -67%          -67%  -77% -79% -88% -93%      -96%
          cps 19.9+- 0.0/s  263%      152%    1%    --         -52%   -54% -59%      -61%    -61% -62%  -65%   -66%          -66%          -67%  -77% -79% -87% -93%      -96%
 gen_no_optim 41.5+- 0.1/s  657%      426%  110%  109%           --    -4% -15%      -18%    -19% -20%  -27%   -29%          -30%          -32%  -52% -56% -74% -86%      -92%
       batseq 43.1+- 0.0/s  687%      447%  118%  117%           4%     -- -11%      -15%    -16% -17%  -24%   -26%          -27%          -29%  -50% -54% -73% -86%      -92%
          gen 48.6+- 0.0/s  787%      516%  146%  144%          17%    13%   --       -4%     -5%  -6%  -14%   -17%          -18%          -20%  -44% -48% -69% -84%      -91%
    coroutine 50.6+- 0.2/s  824%      542%  156%  154%          22%    17%   4%        --   [-2%]  -2%  -11%   -14%          -15%          -17%  -41% -46% -68% -83%      -90%
      std_seq 51.4+- 0.0/s  838%      552%  160%  158%          24%    19%   6%      [2%]      --  -1%   -9%   -12%          -13%          -15%  -40% -45% -68% -83%      -90%
         oseq 51.7+- 0.0/s  845%      556%  162%  160%          25%    20%   6%        2%      1%   --   -9%   -12%          -13%          -15%  -40% -45% -67% -83%      -90%
        ulist 56.6+- 0.1/s  933%      618%  186%  185%          36%    31%  16%       12%     10%   9%    --    -3%           -4%           -7%  -34% -40% -64% -81%      -89%
       uncons 58.5+- 0.1/s  969%      642%  196%  194%          41%    36%  20%       16%     14%  13%    3%     --           -1%           -3%  -32% -38% -63% -80%      -89%
base.sequence 59.2+- 0.1/s  981%      651%  199%  198%          43%    37%  22%       17%     15%  14%    5%     1%            --           -2%  -31% -37% -63% -80%      -89%
core.sequence 60.6+- 0.1/s 1006%      668%  206%  205%          46%    41%  25%       20%     18%  17%    7%     4%            2%            --  -30% -36% -62% -80%      -89%
        g_exn 86.1+- 0.2/s 1471%      991%  335%  333%         107%   100%  77%       70%     67%  66%   52%    47%           45%           42%    --  -9% -46% -71%      -84%
            g 94.3+- 0.1/s 1621%     1095%  376%  374%         127%   119%  94%       86%     83%  82%   67%    61%           59%           56%   10%   -- -41% -68%      -82%
         fold  159+-   0/s 2798%     1912%  702%  698%         283%   268% 227%      214%    209% 207%  180%   171%          168%          162%   84%  68%   -- -47%      -70%
         iter  298+-   0/s 5344%     3681% 1407% 1399%         619%   592% 514%      489%    480% 476%  427%   409%          403%          392%  246% 216%  88%   --      -44%
    streaming  532+-   1/s 9620%     6651% 2591% 2577%        1183%  1135% 996%      952%    936% 929%  841%   809%          799%          779%  519% 465% 235%  79%        --
```

This is a second test WITHOUT the flags '-unbox-closures' & '-unbox-closures-factor 20'.
```
ocamlfind opt -O3  -package iter -package gen -package core_kernel -package base -package batteries -package benchmark -package containers -package oseq -linkpkg bench.ml -o bench.native
./bench.native
Throughputs for "gen", "gen_no_optim", "g", "g_exn", "core.sequence", "base.sequence", "cps", "cps2", "fold", "iter", "list", "lazy_list", "ulist", "uncons", "coroutine", "batseq", "std_seq", "oseq", "streaming" each running 2 times for at least 3 CPU seconds:
          gen:  3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 47.92/s (n=151)
                3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 47.96/s (n=151)
 gen_no_optim:  3.53 WALL ( 3.53 usr +  0.00 sys =  3.53 CPU) @ 41.08/s (n=145)
                3.54 WALL ( 3.54 usr +  0.00 sys =  3.54 CPU) @ 41.01/s (n=145)
            g:  3.30 WALL ( 3.30 usr +  0.00 sys =  3.30 CPU) @ 101.95/s (n=336)
                3.25 WALL ( 3.25 usr +  0.00 sys =  3.25 CPU) @ 103.40/s (n=336)
        g_exn:  3.04 WALL ( 3.04 usr +  0.00 sys =  3.04 CPU) @ 92.66/s (n=282)
                3.03 WALL ( 3.03 usr +  0.00 sys =  3.03 CPU) @ 93.03/s (n=282)
core.sequence:  3.11 WALL ( 3.11 usr +  0.00 sys =  3.11 CPU) @ 60.43/s (n=188)
                3.16 WALL ( 3.16 usr +  0.00 sys =  3.16 CPU) @ 59.47/s (n=188)
base.sequence:  3.34 WALL ( 3.34 usr +  0.00 sys =  3.34 CPU) @ 60.74/s (n=203)
                3.27 WALL ( 3.27 usr +  0.00 sys =  3.27 CPU) @ 62.15/s (n=203)
          cps:  3.16 WALL ( 3.16 usr +  0.00 sys =  3.16 CPU) @ 21.87/s (n=69)
                3.24 WALL ( 3.24 usr +  0.00 sys =  3.24 CPU) @ 21.31/s (n=69)
         cps2:  3.56 WALL ( 3.56 usr +  0.00 sys =  3.56 CPU) @ 24.47/s (n=87)
                3.59 WALL ( 3.59 usr +  0.00 sys =  3.59 CPU) @ 24.23/s (n=87)
         fold:  3.29 WALL ( 3.29 usr +  0.00 sys =  3.29 CPU) @ 158.58/s (n=522)
                3.29 WALL ( 3.29 usr +  0.00 sys =  3.29 CPU) @ 158.63/s (n=522)
         iter:  3.25 WALL ( 3.25 usr +  0.00 sys =  3.25 CPU) @ 640.41/s (n=2081)
                3.29 WALL ( 3.28 usr +  0.00 sys =  3.29 CPU) @ 633.32/s (n=2081)
         list:  3.10 WALL ( 3.08 usr +  0.02 sys =  3.10 CPU) @  5.16/s (n=16)
                3.17 WALL ( 3.16 usr +  0.01 sys =  3.17 CPU) @  5.36/s (n=17)
    lazy_list:  3.13 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @  8.95/s (n=28)
                3.15 WALL ( 3.14 usr +  0.01 sys =  3.14 CPU) @  8.91/s (n=28)
        ulist:  3.14 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 57.64/s (n=181)
                3.15 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 57.57/s (n=181)
       uncons:  3.17 WALL ( 3.17 usr +  0.00 sys =  3.17 CPU) @ 60.25/s (n=191)
                3.16 WALL ( 3.14 usr +  0.02 sys =  3.16 CPU) @ 60.50/s (n=191)
    coroutine:  3.37 WALL ( 3.34 usr +  0.03 sys =  3.37 CPU) @ 51.93/s (n=175)
                3.38 WALL ( 3.34 usr +  0.04 sys =  3.38 CPU) @ 51.81/s (n=175)
       batseq:  3.33 WALL ( 3.30 usr +  0.03 sys =  3.33 CPU) @ 53.81/s (n=179)
                3.32 WALL ( 3.30 usr +  0.02 sys =  3.32 CPU) @ 53.93/s (n=179)
      std_seq:  3.14 WALL ( 3.13 usr +  0.02 sys =  3.14 CPU) @ 52.19/s (n=164)
                3.13 WALL ( 3.11 usr +  0.02 sys =  3.13 CPU) @ 52.38/s (n=164)
         oseq:  3.13 WALL ( 3.10 usr +  0.03 sys =  3.13 CPU) @ 52.43/s (n=164)
                3.12 WALL ( 3.11 usr +  0.02 sys =  3.12 CPU) @ 52.50/s (n=164)
    streaming:  3.16 WALL ( 3.13 usr +  0.03 sys =  3.16 CPU) @ 522.04/s (n=1649)
                3.16 WALL ( 3.14 usr +  0.02 sys =  3.16 CPU) @ 522.53/s (n=1649)
                Rate         list lazy_list   cps  cps2 gen_no_optim   gen coroutine std_seq  oseq batseq ulist core.sequence uncons base.sequence g_exn    g fold streaming iter
         list 5.26+-0.10/s     --      -41%  -76%  -78%         -87%  -89%      -90%    -90%  -90%   -90%  -91%          -91%   -91%          -91%  -94% -95% -97%      -99% -99%
    lazy_list 8.93+-0.02/s    70%        --  -59%  -63%         -78%  -81%      -83%    -83%  -83%   -83%  -85%          -85%   -85%          -85%  -90% -91% -94%      -98% -99%
          cps 21.6+- 0.3/s   311%      142%    --  -11%         -47%  -55%      -58%    -59%  -59%   -60%  -63%          -64%   -64%          -65%  -77% -79% -86%      -96% -97%
         cps2 24.3+- 0.1/s   363%      173%   13%    --         -41%  -49%      -53%    -53%  -54%   -55%  -58%          -59%   -60%          -60%  -74% -76% -85%      -95% -96%
 gen_no_optim 41.0+- 0.0/s   681%      360%   90%   69%           --  -14%      -21%    -21%  -22%   -24%  -29%          -32%   -32%          -33%  -56% -60% -74%      -92% -94%
          gen 47.9+- 0.0/s   812%      437%  122%   97%          17%    --       -8%     -8%   -9%   -11%  -17%          -20%   -21%          -22%  -48% -53% -70%      -91% -92%
    coroutine 51.9+- 0.1/s   886%      481%  140%  113%          26%    8%        --   [-1%]   -1%    -4%  -10%          -13%   -14%          -16%  -44% -49% -67%      -90% -92%
      std_seq 52.3+- 0.1/s   894%      486%  142%  115%          27%    9%      [1%]      -- [-0%]    -3%   -9%          -13%   -13%          -15%  -44% -49% -67%      -90% -92%
         oseq 52.5+- 0.0/s   898%      488%  143%  115%          28%    9%        1%    [0%]    --    -3%   -9%          -12%   -13%          -15%  -43% -49% -67%      -90% -92%
       batseq 53.9+- 0.1/s   924%      503%  150%  121%          31%   12%        4%      3%    3%     --   -6%          -10%   -11%          -12%  -42% -48% -66%      -90% -92%
        ulist 57.6+- 0.0/s   995%      545%  167%  137%          40%   20%       11%     10%   10%     7%    --           -4%    -5%           -6%  -38% -44% -64%      -89% -91%
core.sequence 60.0+- 0.5/s  1040%      572%  178%  146%          46%   25%       16%     15%   14%    11%    4%            --  [-1%]         [-2%]  -35% -42% -62%      -89% -91%
       uncons 60.4+- 0.1/s  1048%      576%  180%  148%          47%   26%       16%     15%   15%    12%    5%          [1%]     --         [-2%]  -35% -41% -62%      -88% -91%
base.sequence 61.4+- 0.7/s  1068%      588%  185%  152%          50%   28%       18%     18%   17%    14%    7%          [2%]   [2%]            --  -34% -40% -61%      -88% -90%
        g_exn 92.8+- 0.2/s  1666%      940%  330%  281%         126%   94%       79%     78%   77%    72%   61%           55%    54%           51%    -- -10% -41%      -82% -85%
            g  103+-   1/s  1852%     1050%  376%  322%         150%  114%       98%     96%   96%    91%   78%           71%    70%           67%   11%   -- -35%      -80% -84%
         fold  159+-   0/s  2916%     1676%  635%  551%         286%  231%      206%    203%  202%   194%  175%          165%   163%          158%   71%  54%   --      -70% -75%
    streaming  522+-   0/s  9832%     5750% 2319% 2045%        1172%  989%      907%    899%  895%   869%  807%          771%   765%          750%  463% 409% 229%        -- -18%
         iter  637+-   3/s 12011%     7033% 2850% 2516%        1452% 1228%     1128%   1118% 1114%  1082% 1006%          962%   955%          937%  586% 520% 302%       22%   --
```
No big differences **EXCEPT** for iter (2X faster).
Interesting, no?

**Comment by Fourchaux** [comment]
A quick test with OCaml 4.08.1 (that is without flambda):
```
With -unbox-closures
ocamlfind opt -O3 -unbox-closures -unbox-closures-factor 20 -package iter
-package gen -package batteries -package benchmark -package containers -package oseq
-linkpkg bench.ml -o bench.native
./bench.native

               Rate        list lazy_list cps2   cps gen_no_optim   gen g_exn coroutine std_seq  oseq batseq ulist uncons    g iter streaming fold
........
        iter 92.3+- 0.0/s 1631%     1285% 340%  338%         167%  165%  150%      144%    101%  100%    99%   83%    56%  22%   --     [-0%] -37%
   streaming 92.5+- 0.1/s 1635%     1288% 341%  339%         167%  166%  151%      144%    101%  101%    99%   84%    57%  23% [0%]        -- -37%
        fold  146+-   0/s 2638%     2090% 595%  593%         322%  320%  295%      285%    218%  217%   215%  190%   147%  94%  58%       58%   --

(-------------------------------------------------------------------------------------------------------------------------------------------------) 

Without -unbox-closures
ocamlfind opt -O3  -package iter -package gen -package batteries -package benchmark
-package containers -package oseq -linkpkg bench.ml -o bench.native
./bench.native

               Rate        list lazy_list cps2   cps gen_no_optim   gen g_exn coroutine std_seq batseq  oseq ulist uncons    g iter streaming fold
........
        iter 92.3+- 0.1/s 1636%     1291% 339%  338%         181%  179%  162%      145%    101%    99%   96%   83%    56%  29%   --       -2% -35%
   streaming 94.4+- 0.0/s 1675%     1322% 349%  348%         187%  185%  168%      150%    105%   104%  101%   87%    59%  31%   2%        -- -34%
        fold  142+-   4/s 2574%     2043% 577%  575%         333%  330%  304%      277%    209%   207%  202%  182%   140%  98%  54%       51%   -- 
```
A (very impressive) draw between iter and streaming for the 2nd place. 🤗

**Comment by c-cube** [comment]
should we commit some results file, too?

**Comment by Fourchaux** [comment]
Maybe only keeping this summary:
```
Test with 4.10.0+flambda (WITH the flags '-unbox-closures' & '-unbox-closures-factor 20').


ocamlfind opt -O3 -unbox-closures -unbox-closures-factor 20 -package iter -package gen -package core_kernel -package base -package batteries -package benchmark -package containers -package oseq -linkpkg bench.ml -o bench.native
./bench.native
Throughputs for "gen", "gen_no_optim", "g", "g_exn", "core.sequence", "base.sequence", "cps", "cps2", "fold", "iter", "list", "lazy_list", "ulist", "uncons", "coroutine", "batseq", "std_seq", "oseq", "streaming" each running 2 times for at least 3 CPU seconds:

                Rate        list lazy_list  cps2   cps gen_no_optim batseq  gen coroutine std_seq oseq ulist uncons base.sequence core.sequence g_exn    g fold iter streaming
         fold  159+-   0/s 2798%     1912%  702%  698%         283%   268% 227%      214%    209% 207%  180%   171%          168%          162%   84%  68%   -- -47%      -70%
         iter  298+-   0/s 5344%     3681% 1407% 1399%         619%   592% 514%      489%    480% 476%  427%   409%          403%          392%  246% 216%  88%   --      -44%
    streaming  532+-   1/s 9620%     6651% 2591% 2577%        1183%  1135% 996%      952%    936% 929%  841%   809%          799%          779%  519% 465% 235%  79%        --

(-------------------------------------------------------------------------------------------------------------------------------------------------) 

Test with 4.10.0+flambda (WITHOUT the flags '-unbox-closures' & '-unbox-closures-factor 20').

ocamlfind opt -O3  -package iter -package gen -package core_kernel -package base -package batteries -package benchmark -package containers -package oseq -linkpkg bench.ml -o bench.native
./bench.native
Throughputs for "gen", "gen_no_optim", "g", "g_exn", "core.sequence", "base.sequence", "cps", "cps2", "fold", "iter", "list", "lazy_list", "ulist", "uncons", "coroutine", "batseq", "std_seq", "oseq", "streaming" each running 2 times for at least 3 CPU seconds:

                Rate         list lazy_list   cps  cps2 gen_no_optim   gen coroutine std_seq  oseq batseq ulist core.sequence uncons base.sequence g_exn    g fold streaming iter
         fold  159+-   0/s  2916%     1676%  635%  551%         286%  231%      206%    203%  202%   194%  175%          165%   163%          158%   71%  54%   --      -70% -75%
    streaming  522+-   0/s  9832%     5750% 2319% 2045%        1172%  989%      907%    899%  895%   869%  807%          771%   765%          750%  463% 409% 229%        -- -18%
         iter  637+-   3/s 12011%     7033% 2850% 2516%        1452% 1228%     1128%   1118% 1114%  1082% 1006%          962%   955%          937%  586% 520% 302%       22%   --

(-------------------------------------------------------------------------------------------------------------------------------------------------) 

Test with OCaml 4.08.1 (NO flambda - WITH the flags '-unbox-closures' & '-unbox-closures-factor 20').

ocamlfind opt -O3 -unbox-closures -unbox-closures-factor 20 -package iter
-package gen -package batteries -package benchmark -package containers -package oseq
-linkpkg bench.ml -o bench.native
./bench.native

               Rate        list lazy_list cps2   cps gen_no_optim   gen g_exn coroutine std_seq  oseq batseq ulist uncons    g iter streaming fold
        iter 92.3+- 0.0/s 1631%     1285% 340%  338%         167%  165%  150%      144%    101%  100%    99%   83%    56%  22%   --     [-0%] -37%
   streaming 92.5+- 0.1/s 1635%     1288% 341%  339%         167%  166%  151%      144%    101%  101%    99%   84%    57%  23% [0%]        -- -37%
        fold  146+-   0/s 2638%     2090% 595%  593%         322%  320%  295%      285%    218%  217%   215%  190%   147%  94%  58%       58%   --

(-------------------------------------------------------------------------------------------------------------------------------------------------) 

Test with OCaml 4.08.1 (NO flambda - WITHOUT the flags '-unbox-closures' & '-unbox-closures-factor 20').

ocamlfind opt -O3  -package iter -package gen -package batteries -package benchmark
-package containers -package oseq -linkpkg bench.ml -o bench.native
./bench.native

               Rate        list lazy_list cps2   cps gen_no_optim   gen g_exn coroutine std_seq batseq  oseq ulist uncons    g iter streaming fold
        iter 92.3+- 0.1/s 1636%     1291% 339%  338%         181%  179%  162%      145%    101%    99%   96%   83%    56%  29%   --       -2% -35%
   streaming 94.4+- 0.0/s 1675%     1322% 349%  348%         187%  185%  168%      150%    105%   104%  101%   87%    59%  31%   2%        -- -34%
        fold  142+-   4/s 2574%     2043% 577%  575%         333%  330%  304%      277%    209%   207%  202%  182%   140%  98%  54%       51%   -- 

(-------------------------------------------------------------------------------------------------------------------------------------------------) 

```

**Comment by rizo** [comment]
Wow, pretty interesting indeed, @Fourchaux!

One note about `fold`: it seems to perform really well, but unfortunately the model is pretty useless given that it does not implement early termination at all (i.e. something like `take` would not limit the stream).

**Pull request merged**
